### ISSUE TITLE
The type or namespace name 'SpriteCollection' could not be found

### ISSUE THREAD

**Issue by hippogamesunity** [hippogamesunity/FantasyHeroesHub#1]
From email:
> Hi!
> 
> I love your asset Fantasy Heroes: Character Editor! It works while editing in Unity and i can it inside Unity, but i can't Build it to an .exe or .apk...
> I have tried to Reimport the asset multiple times and i have tried to create a clean project and import the asset in there, which also didn't work.
> Do you maybe know what might be the problem? I have Unity version 5.6.1f1 Personal(64bit).
> 
> Kind regards,
> 
> Jeremy Pietersz

**Comment by hippogamesunity** [comment]
Will be fixed in next update. As a workaround you can change #if UNITY_EDITOR directive location in SpriteCollection.cs.
It should hide only class methods, not properties.

**Comment by luckmager** [comment]
Allright thank you very much! :)
